const Task = require('../models/taskModel');
const User = require('../models/userModel');

const initTasks = async () => {
    const userCase1 = await User.findOne({ email: 'user1@example.com' }).select('lastName firstName phone email');
    const userCase2 = await User.findOne({ email: 'user2@example.com' }).select('lastName firstName phone email');
    const userCase3 = await User.findOne({
        email: 'user4@example.com',
    }).select('lastName firstName phone email');
    const userCase4 = await User.findOne({
        email: 'user5@example.com',
    }).select('lastName firstName phone email');
    const userCase5 = await User.findOne({ email: 'user6@example.com' }).select('lastName firstName phone email');
    const tasks = [
        {
            userId: userCase1._id,
            status: 'confirmed',
            title: '急！幫忙代購王國之淚',
            category: '排隊代購',
            description: '很急，5/11 晚上請在信義店前排隊代購，12:00準時想拿到遊戲片',
            salary: 300,
            exposurePlan: '黃金曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/7d6df9b6-ac30-4ece-942a-a070f2b929af.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=QejWgLmbVbSANXfrP8AFyipT2qoGV0qML%2FtJ1g8%2FczHZkF4pl6VUGNiFK%2FkISJdWysIbT5qXvSVgBaN%2FxUXs3uSJzrtgbl8FQKnudKTqYf8kNiPvIPbJoX58SotSiPxFiRCcJjiPSkXl%2F70VcipyFPe9MrZSBSvUHtLfiS3xWMZO1j%2FesZRSosAX8ZsSHqrea0IcfitWcoFYr9T3LK1RKeuGrao%2B7aFNKhqN5rJSUMY1ADP3MmRYwwY4VugC8kmrZ7DtjCyzijW2NE9vCG169ZVsrC%2BoxSv9FQwwGRtrAkBG31EPS4hKV9nDv4WxcHAC4xTK7YGLyee5jaz37SQNLg%3D%3D',
                'https://storage.googleapis.com/superhandy.appspot.com/images/737e231e-69a0-4fa3-a5f3-1df85558bf7e.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=pbnuAnhwz2pzMbb0y8APg9OM0k1lA924jN9Flot%2B6vTyesi1R5Nm0n6HA1tFaed4c%2BN8MFeYGoUZmH8ml7yvyWspGirZ9WVpVSnJS6ecnKlCZh7V2tpHqBMR71w7NIaMt1%2FB6k%2F8x9O80iCMmpmSGkxGPJ%2BuBS5SZ8ATupE3j1MdGF2duDupEkj9%2F6mSMWhdwAK5XEXFUwKkk6g1wcpEJ7JlsOLvF%2BjikuRIghQB7nL7sBs43MxpR1rRDvdg76p2hwcrmi2q2EdEKQZpp%2BKAE7oXrT8rcxl9vGxwIJmtw4htYiCqOektPYQHPXR9hBatLOOV0j8hbDPOmAYhG8xHNQ%3D%3D',
            ],
            contactInfo: {
                name: `${userCase1.lastName}${userCase1.firstName}`,
                phone: userCase1.phone,
                email: userCase1.email,
            },
            location: {
                city: '臺北市',
                dist: '信義區',
                address: '松智路17號',
                longitude: 121.5659555,
                latitude: 25.0343073,
            },
            isUrgent: false,
            helpers: [
                {
                    helperId: userCase2._id,
                    status: 'paired',
                },
                {
                    helperId: userCase3._id,
                    status: 'unpaired',
                },
                {
                    helperId: userCase5._id,
                    status: 'unpaired',
                },
            ],
            time: {
                createdAt: new Date('2023-05-12T12:34:56'),
                updatedAt: new Date('2023-05-19T19:15:50'),
                publishedAt: new Date('2023-05-13T13:34:56'),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: new Date('2023-05-16T13:34:56'),
                submittedAt: new Date('2023-05-17T13:55:56'),
                confirmedAt: new Date('2023-05-19T19:15:50'),
                completedAt: null,
                expiredAt: new Date('2023-06-13T13:34:56'),
            },
            submittedInfo: [
                {
                    role: '幫手',
                    imgUrls: [
                        'https://storage.googleapis.com/superhandy.appspot.com/images/c0da4c1b-e05c-49fa-b942-90c35ba75bb9.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=NU2w89IOhOQ4j%2Bo5PaIlksJOp8GbzHTRGXkGZPMEaPXRGE9aBKYZLMRArlZ2rV%2BIBylf%2FzfppcmUaOs5ccj8P0hZxgT4P29glScrZ%2BvZNdZLu4SrF6o1HdHWRlidGXDsM1RE6o1aiMHLtl2qKHYdBGao%2BS2tKGVQivNQn1Hvw23fGZdac82WPiKRFLF7DtB%2BShtaiu9PkXn0O2FtN09WVLHfe%2F2foWblwe2bt7JKZhJJQfXushOsEfyRugUk3qDlXk%2FWue2lj9pZY43DUhcpVRdGf%2Bdk4b0Rv1JjU6fCumnh48Yaub5H7FdPB5JomRjseiev3j7ZrzAFbf7MGWggow%3D%3D',
                    ],
                    comment: '這個任務簡單啦',
                    createAt: new Date('2023-05-17T13:55:56'),
                },
            ],
        },
        {
            userId: userCase1._id,
            status: 'published',
            title: '幫忙打王國之淚的Boss',
            category: '人力派遣',
            description: 'Boss 好難打，急徵高手幫忙，不可以花我太多素材，意者私聊',
            salary: 500,
            exposurePlan: '黃金曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/27cf2428-96dc-48ec-bb50-a14c59b44a5e.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=Ev8Mgk1SCQ8CeLj47jlDNJ6M4PU0FJ8LcZk9TMvVPPkFo6KAyod%2B2q8zaV4Hyg7tpKiKKORYxRN0%2FdA7vPMBBzKINxJYpVxMHVg94HmPx1pG28VREk%2FvyHuLiBpHtIfG8gEXFeJbY7%2FJqtLW%2FQDbCK8kKTLwkPRXFlFiAtDl%2BW1KQTu2l%2Bv%2BLvBPpUGYYdR40Wcd%2FYs0tN%2F8kd%2BL7UkKg8iNy3AxPohVlakv5xmHM32VvXWJWoxQ3wuy4FVPZ%2Fpebz7uwkjht5c9YHWol5GddRK%2BPHs5IcpecUvMitIMy%2Fr4tRiouq2Xahv6NqAN317GmsSvxWdKYvxhemNgpbzPKA%3D%3D',
                'https://storage.googleapis.com/superhandy.appspot.com/images/655c362d-9b8c-4e2f-b289-f75917177525.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=kQz1YDHpwhIix8633VWCcYpssme3ldDH3TN5U9hM07Q2zzHy4LMwQEJ8akGegGpAv8vY%2BBGV4aYZ1hY4MiNWNHkafEwR7Wk8VYRMMYFcdeU7NRbv6U%2B5GUJKEFaZFs0xcajp1AJxsIYkuIc4JxqQZnBnhZH7jVBjnaMtWB%2B5WrNLcoRRpdzf64Ngf48KfCUoa7W8xAmTt51OblVX%2FzY1RxY9Q9v8n2PNBAn7Ge2JOLsCYQ%2B9QDMhkxhRefH9aXUkeEkZycstJWxEnm9rpKnmCpkpkrJeSmvw%2BdD42gFA5RVN8UVN%2Fag%2FS1AyRzR2M9RIXMAyVM1wtuX8fhAxRd1oFg%3D%3D',
                'https://storage.googleapis.com/superhandy.appspot.com/images/5853640a-267a-4a0d-b3d8-30af4785643b.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=oIRETi1rIiaNhZUPJTdfvT5CbCYiRjYkZFqIm4pr7L7k%2FkamWokiuN4u42JXW7ud%2Fr%2BotSbU%2BzXbpRt4g9JzZqbA4ax85JZyoSQRKWsyWrx3CI5fexnLlf1u9q8uE2VLAjQyyJqOJol6fcBrzuhAjh25jDyPBwriZiAIOo4pYmdPGfSV1S9jUBgFXqAtZHvA%2BfQtLBc3cyE6viGJv4L5n%2FaZfynMwTZAsb2%2F56bo1z2xJ8guEm4ItjN%2BPLKyZg%2BZENiFoCA5zJ7aihMn%2BzWaPYB1Qkb1RiJakW8xLjEmSvdlLjpl9WaloXwXVQUftjrxuD%2Bm4qvH4pfNy3UsBEWSNA%3D%3D',
            ],
            contactInfo: {
                name: `${userCase1.lastName}${userCase1.firstName}`,
                phone: userCase1.phone,
                email: userCase1.email,
            },
            location: {
                city: '臺北市',
                dist: '信義區',
                address: '基隆路300號',
                longitude: 121.5644267,
                latitude: 25.0412214,
            },
            isUrgent: false,
            helpers: [
                {
                    helperId: userCase5._id,
                    status: 'waiting',
                },
                {
                    helperId: userCase3._id,
                    status: 'waiting',
                },
                {
                    helperId: userCase2._id,
                    status: 'waiting',
                },
            ],
            time: {
                createdAt: new Date(),
                updatedAt: new Date(),
                publishedAt: new Date(),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: null,
                submittedAt: null,
                confirmedAt: null,
                completedAt: null,
                expiredAt: new Date(new Date().setDate(new Date().getDate() + 7)),
            },
        },
        {
            userId: userCase1._id,
            status: 'completed',
            title: '陪我家狗玩',
            category: '寵物陪伴',
            description: '我家有黃金獵犬，但我這禮拜很忙，請幫我 2/20 早上 8 點來歌唱大樓找我，並帶他去附近公園陪他散步',
            salary: 300,
            exposurePlan: '黃金曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/ca47c054-c0cc-4246-97cb-e9b2806a35cb.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=F4nudMD87t41P%2FplEfViMONpnXzHzjiyul1iYk4tymohibhpolVuPjaSieatiDg311630Z4ZYUwir2jw5jD1OaCVo7QQXSz0mh3Pu18%2FE1VxdWH0GhrabdnVidjBbkdcqnUF8bTrSJic1%2F0paPfr1o7amcU7KhiiYbG%2BsxO1wMDLWZYOg3oOnUIBTZB99D4JrHdKhbUZtKshIKrB7yLuY2YSwaYdxJnNFM1WQUKy11RXILdhFz%2FJlJKGD0eWd70cuHk3fzb9E5i5J91EKqxMTXNg7zzr0AC6GbkROeVwCCBvh1HoneZlgpBn5ya0f%2BTObR8LMPmUpfi5oHTWdDt13w%3D%3D',
                'https://storage.googleapis.com/superhandy.appspot.com/images/e3a8b396-1572-4a7a-9097-f3d0891539cf.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=SKsFvBRhTH0ze6GN4kNMjand2YwRIWpyWMafKcQI8y05EVmfQuIWamEK9A7is8xCYdE652TjNnkzDVOUQUjO%2FFnfmw3qa8TDaOdIoflmhHPUjC0nNIOIm%2FNL5JDFjxqrg2sYMBOeuddljt3Mj14dlidliRicAf4B6HES%2FLXvLQYsqELx1vbyhj8lhxZBIuvRR806SCtNxcvGQYlqY50e6InsiWEpxpiQNHoY6NCvs3Z1yZAbbKVK2a0Lr%2F0mNl4hRkDkOBYFyCQWpI2psAub3IE8Bo3EiNmbDDADqWBAblZlCexkh%2FfZBW4o0y6V5cqVcL87ppoZMvNIxafzMuFUIA%3D%3D',
            ],
            contactInfo: {
                name: `${userCase1.lastName}${userCase1.firstName}`,
                phone: userCase1.phone,
                email: userCase1.email,
            },
            location: {
                city: '臺北市',
                dist: '松山區',
                address: '復興北路15號',
                longitude: 121.5442703,
                latitude: 25.0486251,
            },
            isUrgent: false,
            currentHelperId: userCase5._id,
            helpers: [
                {
                    helperId: userCase5._id,
                    status: 'paired',
                },
                {
                    helperId: userCase3._id,
                    status: 'unpaired',
                },
                {
                    helperId: userCase2._id,
                    status: 'unpaired',
                },
            ],
            time: {
                createdAt: new Date('2023-01-30T12:34:56'),
                updatedAt: new Date('2023-02-23T08:19:50'),
                publishedAt: new Date('2023-02-15T13:34:56'),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: new Date('2023-02-16T13:34:56'),
                submittedAt: new Date('2023-02-17T13:55:56'),
                confirmedAt: new Date('2023-02-19T19:15:50'),
                completedAt: new Date('2023-02-23T08:19:50'),
                expiredAt: new Date('2023-03-15T13:34:56'),
            },
            submittedInfo: [
                {
                    role: '幫手',
                    imgUrls: [
                        'https://storage.googleapis.com/superhandy.appspot.com/images/e3a8b396-1572-4a7a-9097-f3d0891539cf.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=SKsFvBRhTH0ze6GN4kNMjand2YwRIWpyWMafKcQI8y05EVmfQuIWamEK9A7is8xCYdE652TjNnkzDVOUQUjO%2FFnfmw3qa8TDaOdIoflmhHPUjC0nNIOIm%2FNL5JDFjxqrg2sYMBOeuddljt3Mj14dlidliRicAf4B6HES%2FLXvLQYsqELx1vbyhj8lhxZBIuvRR806SCtNxcvGQYlqY50e6InsiWEpxpiQNHoY6NCvs3Z1yZAbbKVK2a0Lr%2F0mNl4hRkDkOBYFyCQWpI2psAub3IE8Bo3EiNmbDDADqWBAblZlCexkh%2FfZBW4o0y6V5cqVcL87ppoZMvNIxafzMuFUIA%3D%3D',
                    ],
                    comment: '你家的狗很乖很聽話',
                    createAt: new Date('2023-02-17T13:55:56'),
                },
            ],
        },
        {
            userId: userCase2._id,
            status: 'completed',
            title: '幫忙做畢業專題',
            category: '文書處理',
            description: '我目前正在進行一份有關自然語言處理的畢業專題，需要一位有相關經驗的助理幫忙實驗和分析數據。',
            salary: 1300,
            exposurePlan: '限時黃金曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/4ca420a9-244c-4afd-b15a-35f145cb7061.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=AehjIhyAp%2F3rApGEiybN9H9IdaSON6hQIKMhAluH%2F8h0QUmD5D2MB%2B%2BrPkh5TSR7aSIUKKklAMM8v2GZs%2BTpcrz8UkjDISCpq0wwBTios3Ce1dOpjEWTnQEKIHA4jc6bcs7fXYFuiVuaOfeS0lhJ0J%2BcZoHe4uasI3mdtVibiEsjXYQh%2FPw4nxo%2FDOo10oggIcxkW0VPnrWVj4tHv3fzeLWAF2FPCyRGas6zGGEvE62fsdw0aWEhYTUNIyllHTQPTsrWgaaXoe0R1KHigbtzkUEPdcGf5qhQTMcZj0t6n6nnvMR6jX%2FQmoPRxynCA50D7xZEm%2BWmtPtSFErNbjbLNw%3D%3D',
            ],
            contactInfo: {
                name: `${userCase2.lastName}${userCase2.firstName}`,
                phone: userCase2.phone,
                email: userCase2.email,
            },
            location: {
                city: '臺北市',
                dist: '松山區',
                address: '羅斯福路四段1號',
                longitude: 121.5339903,
                latitude: 25.0184919,
            },
            isUrgent: true,
            currentHelperId: userCase1._id,
            helpers: [
                {
                    helperId: userCase1._id,
                    status: 'paired',
                },
                {
                    helperId: userCase3._id,
                    status: 'unpaired',
                },
                {
                    helperId: userCase5._id,
                    status: 'unpaired',
                },
            ],
            time: {
                createdAt: new Date('2023-05-01T09:00:00'),
                updatedAt: new Date('2023-05-06T09:00:00'),
                publishedAt: new Date('2023-05-01T11:00:00'),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: new Date('2023-05-03T09:00:00'),
                submittedAt: new Date('2023-05-04T09:00:00'),
                confirmedAt: new Date('2023-05-05T09:00:00'),
                completedAt: new Date('2023-05-06T09:00:00'),
                expiredAt: new Date('2023-05-08T11:00:00'),
            },
            submittedInfo: [
                {
                    role: '幫手',
                    imgUrls: [
                        'https://storage.googleapis.com/superhandy.appspot.com/images/3234e78e-7bff-4be8-854f-8ce28866892d.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=TC0LWwaA0INclWGIvqip3h5y5Bget8WQQE76NfEPE4jkw%2BIk9btuvnTYUz%2FYaKqOBPjBW%2FmrtQUDErNCN9PqlZTE2NoUxpkphgsBF%2FFqxLaSWhPKVHE%2BnUibAPONCGW3KWa2Ga4ryL0BMPhe1VrawXZ4j25mH5xBMY8wORThdrmhMI0Qq5%2Br1RXIW%2BOXLWLO6EFrktNUOhthSj62opeLekbiBIzbUzSRQz5PNPYBZ5dKLE4Y%2F8YzPg4hj%2F5RTS%2F5loP8UsnDh7nRII%2FezRV29yJ2KHResrc%2BtBhxA1snfSqNcLRQNfbNQ0tIe2XkdOy4X7N3jJdZpVpnV9D5MaxT2w%3D%3D',
                    ],
                    comment: '這份報告有夠難做，NLP 難啊',
                    createAt: new Date('2023-05-04T09:00:00'),
                },
            ],
        },
        {
            userId: userCase3._id,
            status: 'completed',
            title: '協助居家清潔',
            category: '清潔外包',
            description: '需要一位勤快且細心的人來協助居家清潔，家裡有一些難以清潔的區域需要特別注意。',
            salary: 666,
            exposurePlan: '一般曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/e68a9ee4-ce28-4dda-ac45-f7463113063e.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=Pr5wfciWCDqtwSKl05xMIgBsM%2FKgEkkeGCdmp%2BinNG%2BeWFHDZOL0d5tPxZYW1Y8hdiFBu83Q6cpMQ1M9xNCAeW%2BFeKehMe4JkYJBY42IhN%2BvreGpHexMVF2kGnqKVLoBCSfaT6Y%2B2Cw%2BQ%2FX3%2F7iXkHqEW%2BXkubSLl0SuEbScAwBZ%2FQykCGIxB5tH%2FjTbr1NFvzDgBWJJp9JuD2gRV28BgYMWLPWFDxufmMjxYQYKsv5d5CdYXBmmy5BHrD9%2FoTPyDUvrBNKoqIsW92ikT3TFfussHlkaKwyhU5taQ8AjF9pizAMcaBTXS0MWQ%2FP6kRVxfXjiFIpsIzPL7Bb7I5zxeA%3D%3D',
            ],
            contactInfo: {
                name: `${userCase3.lastName}${userCase3.firstName}`,
                phone: userCase3.phone,
                email: userCase3.email,
            },
            location: {
                city: '新北市',
                dist: '板橋區',
                address: '新站路20號',
                landmark: '板橋火車站',
                longitude: 121.4663595,
                latitude: 25.0132041,
            },
            isUrgent: false,
            currentHelperId: userCase1._id,
            helpers: [
                {
                    helperId: userCase1._id,
                    status: 'paired',
                },
                {
                    helperId: userCase2._id,
                    status: 'unpaired',
                },
                {
                    helperId: userCase5._id,
                    status: 'unpaired',
                },
            ],
            time: {
                createdAt: new Date('2023-04-02T18:00:00'),
                updatedAt: new Date('2023-04-17T09:00:00'),
                publishedAt: new Date('2023-04-02T20:00:00'),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: new Date('2023-04-13T09:00:00'),
                submittedAt: new Date('2023-04-17T09:00:00'),
                confirmedAt: new Date('2023-04-18T09:00:00'),
                completedAt: new Date('2023-04-19T09:00:00'),
                expiredAt: new Date('2023-05-02T20:00:00'),
            },
            submittedInfo: [
                {
                    role: '幫手',
                    imgUrls: [
                        'https://storage.googleapis.com/superhandy.appspot.com/images/e68a9ee4-ce28-4dda-ac45-f7463113063e.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=Pr5wfciWCDqtwSKl05xMIgBsM%2FKgEkkeGCdmp%2BinNG%2BeWFHDZOL0d5tPxZYW1Y8hdiFBu83Q6cpMQ1M9xNCAeW%2BFeKehMe4JkYJBY42IhN%2BvreGpHexMVF2kGnqKVLoBCSfaT6Y%2B2Cw%2BQ%2FX3%2F7iXkHqEW%2BXkubSLl0SuEbScAwBZ%2FQykCGIxB5tH%2FjTbr1NFvzDgBWJJp9JuD2gRV28BgYMWLPWFDxufmMjxYQYKsv5d5CdYXBmmy5BHrD9%2FoTPyDUvrBNKoqIsW92ikT3TFfussHlkaKwyhU5taQ8AjF9pizAMcaBTXS0MWQ%2FP6kRVxfXjiFIpsIzPL7Bb7I5zxeA%3D%3D',
                    ],
                    comment: '這份工作比想像中還要累，但收穫也很多。',
                    createAt: new Date('2023-04-17T09:00:00'),
                },
            ],
        },
        {
            userId: userCase4._id,
            status: 'completed',
            title: '陪我練習開車',
            category: '其他內容',
            description: '我最近剛考到駕照，但還不太有經驗，需要一位有開車經驗的人來陪我練習開車，希望能有耐心且細心的教練。',
            salary: 567,
            exposurePlan: '限時曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/7df19da5-cbcf-4b71-8a5e-62a318a864da.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=hl2TIsZQMu5IXz4SMH9o7PIYkZ2xbcrgrh7iBH6sm2L7B%2Fj4G3MT97IUD30GAEqM8XzgWupO9j8y%2BHP6Mr0NQ0Sw1HpWRIrjKDlAz%2FVlHiYGlMM1WOjzphKga2STrGWGBEPF1c8Hlh3bkjt%2BQ%2BP%2BOFUGw%2B2zamJYRbB1Qc0XAA4AygCvgvCUWTruQCf6sErjCjOK3q21a8z8NnR6BZes6h%2BDtZ8xQt63B1rJ%2BgNCMaiLtqOLHTnYmZBhA4KJaiWUt%2Bad9qZ6QXlP%2F4%2BD6N9eTj9t5QDBim4LkcX9%2BBKT7m%2BxMQme2MPNElDXvkj3Gh7pMOiaLXikFh1WckpKy%2BT6vg%3D%3D',
            ],
            contactInfo: {
                name: `${userCase4.lastName}${userCase4.firstName}`,
                phone: userCase4.phone,
                email: userCase4.email,
            },
            location: {
                city: '臺中市',
                dist: '南區',
                address: '復興南路二段240號',
                longitude: 120.6624117,
                latitude: 24.1208445,
            },
            isUrgent: false,
            currentHelperId: userCase1._id,
            helpers: [
                {
                    helperId: userCase1._id,
                    status: 'paired',
                },
                {
                    helperId: userCase2._id,
                    status: 'unpaired',
                },
                {
                    helperId: userCase5._id,
                    status: 'unpaired',
                },
                {
                    helperId: userCase3._id,
                    status: 'unpaired',
                },
            ],
            time: {
                createdAt: new Date('2023-05-02T18:00:00'),
                updatedAt: new Date('2023-05-03T09:00:00'),
                publishedAt: new Date('2023-05-04T20:00:00'),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: new Date('2023-05-13T09:00:00'),
                submittedAt: new Date('2023-05-17T09:00:00'),
                confirmedAt: new Date('2023-05-18T09:00:00'),
                completedAt: new Date('2023-05-19T09:00:00'),
                expiredAt: new Date('2023-05-11T18:00:00'),
            },
            submittedInfo: [
                {
                    role: '幫手',
                    imgUrls: [
                        'https://storage.googleapis.com/superhandy.appspot.com/images/7df19da5-cbcf-4b71-8a5e-62a318a864da.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=hl2TIsZQMu5IXz4SMH9o7PIYkZ2xbcrgrh7iBH6sm2L7B%2Fj4G3MT97IUD30GAEqM8XzgWupO9j8y%2BHP6Mr0NQ0Sw1HpWRIrjKDlAz%2FVlHiYGlMM1WOjzphKga2STrGWGBEPF1c8Hlh3bkjt%2BQ%2BP%2BOFUGw%2B2zamJYRbB1Qc0XAA4AygCvgvCUWTruQCf6sErjCjOK3q21a8z8NnR6BZes6h%2BDtZ8xQt63B1rJ%2BgNCMaiLtqOLHTnYmZBhA4KJaiWUt%2Bad9qZ6QXlP%2F4%2BD6N9eTj9t5QDBim4LkcX9%2BBKT7m%2BxMQme2MPNElDXvkj3Gh7pMOiaLXikFh1WckpKy%2BT6vg%3D%3D',
                    ],
                    comment: '學生學得很快，很有耐心。',
                    createAt: new Date('2023-05-17T09:00:00'),
                },
            ],
        },
        {
            userId: userCase5._id,
            status: 'completed',
            title: 'Notion 教學',
            category: '電腦教學',
            description: '需要一位有經驗的人來教我如何使用 Notion 管理自己的筆記和待辦事項。',
            salary: 999,
            exposurePlan: '限時黃金曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/938c5135-1286-4c3b-b6b5-a2d7d134602f.png?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=oYMU6KiwmNT68yWvTmdHWSIJTilHbjwWODqYbUZ1CagffUJfdX7S6JWfMAyqLGFccWxeOuvs8mM0SIqtkvPV%2Bi3gkY55XE%2FNi%2BElLEqrLZda8R0ngu6SElP9SFyD%2BLTcfH6Y7y%2Bayza2HaBoxINntEa94d40cDw5fDYFkumTWafqDGmXjiWGQHmaPZK0v2t0qKGKPB%2By6ZJUOJ0DMwlyVECVgV0u4Lcr9r609tSkzmbNyc4jSEhfaE1eUUo4L1HE4CNCEBFycCPMy7gpIDF7HRS04TL0foIt%2BLqv9nM8dy1y7CaXrbkTeWv%2B6vHa3QrRH0haqRx%2Ffo5CIJJ%2Bb2HHgg%3D%3D',
            ],
            contactInfo: {
                name: `${userCase5.lastName}${userCase5.firstName}`,
                phone: userCase5.phone,
                email: userCase5.email,
            },
            location: {
                city: '臺北市',
                dist: '中正區',
                address: '信義路1號',
                longitude: 121.5748662,
                latitude: 25.0219844,
            },
            isUrgent: false,
            currentHelperId: userCase2._id,
            helpers: [
                {
                    helperId: userCase2._id,
                    status: 'paired',
                },
                {
                    helperId: userCase1._id,
                    status: 'unpaired',
                },
                {
                    helperId: userCase2._id,
                    status: 'unpaired',
                },
                {
                    helperId: userCase3._id,
                    status: 'unpaired',
                },
            ],
            time: {
                createdAt: new Date('2023-05-03T18:00:00'),
                updatedAt: new Date('2023-06-01T10:00:00'),
                publishedAt: new Date('2023-05-02T20:00:00'),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: new Date('2023-05-10T09:00:00'),
                submittedAt: new Date('2023-05-12T05:00:00'),
                confirmedAt: new Date('2023-05-13T09:00:00'),
                completedAt: new Date('2023-05-16T10:00:00'),
                expiredAt: new Date('2023-05-09T20:00:00'),
            },
            submittedInfo: [
                {
                    role: '幫手',
                    imgUrls: [
                        'https://storage.googleapis.com/superhandy.appspot.com/images/938c5135-1286-4c3b-b6b5-a2d7d134602f.png?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=oYMU6KiwmNT68yWvTmdHWSIJTilHbjwWODqYbUZ1CagffUJfdX7S6JWfMAyqLGFccWxeOuvs8mM0SIqtkvPV%2Bi3gkY55XE%2FNi%2BElLEqrLZda8R0ngu6SElP9SFyD%2BLTcfH6Y7y%2Bayza2HaBoxINntEa94d40cDw5fDYFkumTWafqDGmXjiWGQHmaPZK0v2t0qKGKPB%2By6ZJUOJ0DMwlyVECVgV0u4Lcr9r609tSkzmbNyc4jSEhfaE1eUUo4L1HE4CNCEBFycCPMy7gpIDF7HRS04TL0foIt%2BLqv9nM8dy1y7CaXrbkTeWv%2B6vHa3QrRH0haqRx%2Ffo5CIJJ%2Bb2HHgg%3D%3D',
                    ],
                    comment: '',
                    createAt: new Date('2023-05-12T05:00:00'),
                },
            ],
        },
        {
            userId: userCase2._id,
            status: 'published',
            title: '兼職家教數學',
            category: '家教陪讀',
            description: '需要幫忙教授數學科目，學生理解能力稍弱，時薪400，急需人手。',
            salary: 400,
            exposurePlan: '黃金曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/0ad3b90d-4958-4690-b89f-574833ffb673.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=i99vcoya6YvanXzSjEf3lR74T7%2Bd1GbSUr2IY9aD1uGMBD6RyyVH%2BVdAtbgoA56fOMeYmk%2BidqWyIBBbeSKG3jvXqAibofRGysqWV7CYXWRa%2Bc7qT02wu%2FgRcJX5UBjxLLu2a%2BszXluH1Rdpg1NPlN3h6HihZLp0IEW%2FHUDoZ5hsN9rtheBs4ZPPe%2Faf12iev%2B6CHtVdRiv67olWITj8lkd52pKlE43PQJA7IozApIujLZwvNDdiXqYhCZplGLEtOSdERfYGnxHga%2F0dyplzGi7slJYK57oXynO8V%2BW185I11JKNSMq%2FfNSVBoxEUVW8PT0VeW5MOlrOy0fWTSrAVQ%3D%3D',
            ],
            contactInfo: {
                name: `${userCase1.lastName}${userCase1.firstName}`,
                phone: userCase1.phone,
                email: userCase1.email,
            },
            location: {
                city: '臺北市',
                dist: '中山區',
                address: '忠孝東路二段100號',
                longitude: 121.5304479,
                latitude: 25.042823,
            },
            isUrgent: false,
            helpers: [
                {
                    helperId: userCase5._id,
                    status: 'waiting',
                },
                {
                    helperId: userCase4._id,
                    status: 'waiting',
                },
            ],
            time: {
                createdAt: new Date(new Date().setDate(new Date().getDate() - 1)),
                updatedAt: new Date(new Date().setDate(new Date().getDate() - 1)),
                publishedAt: new Date(new Date().setDate(new Date().getDate() - 1)),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: null,
                submittedAt: null,
                confirmedAt: null,
                completedAt: null,
                expiredAt: new Date(new Date().setDate(new Date().getDate() + 29)),
            },
        },
        {
            userId: userCase1._id,
            status: 'published',
            title: '需求短期家庭清潔工',
            category: '居家服務',
            description: '家中需要進行全面清潔，時薪350，需求立即開始。',
            salary: 350,
            exposurePlan: '黃金曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/e68a9ee4-ce28-4dda-ac45-f7463113063e.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=Pr5wfciWCDqtwSKl05xMIgBsM%2FKgEkkeGCdmp%2BinNG%2BeWFHDZOL0d5tPxZYW1Y8hdiFBu83Q6cpMQ1M9xNCAeW%2BFeKehMe4JkYJBY42IhN%2BvreGpHexMVF2kGnqKVLoBCSfaT6Y%2B2Cw%2BQ%2FX3%2F7iXkHqEW%2BXkubSLl0SuEbScAwBZ%2FQykCGIxB5tH%2FjTbr1NFvzDgBWJJp9JuD2gRV28BgYMWLPWFDxufmMjxYQYKsv5d5CdYXBmmy5BHrD9%2FoTPyDUvrBNKoqIsW92ikT3TFfussHlkaKwyhU5taQ8AjF9pizAMcaBTXS0MWQ%2FP6kRVxfXjiFIpsIzPL7Bb7I5zxeA%3D%3D',
            ],
            contactInfo: {
                name: `${userCase1.lastName}${userCase1.firstName}`,
                phone: userCase1.phone,
                email: userCase1.email,
            },
            location: {
                city: '臺北市',
                dist: '大安區',
                address: '忠孝東路三段200號',
                longitude: 121.5395262,
                latitude: 25.0414373,
            },
            isUrgent: false,
            helpers: [
                {
                    helperId: userCase5._id,
                    status: 'waiting',
                },
                {
                    helperId: userCase3._id,
                    status: 'waiting',
                },
                {
                    helperId: userCase2._id,
                    status: 'waiting',
                },
            ],
            time: {
                createdAt: new Date(new Date().setDate(new Date().getDate() - 1)),
                updatedAt: new Date(new Date().setDate(new Date().getDate() - 1)),
                publishedAt: new Date(new Date().setDate(new Date().getDate() - 1)),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: null,
                submittedAt: null,
                confirmedAt: null,
                completedAt: null,
                expiredAt: new Date(new Date().setDate(new Date().getDate() + 29)),
            },
        },
        {
            userId: userCase1._id,
            status: 'published',
            title: '需要網頁設計師',
            category: '網頁設計',
            description: '尋找有經驗的網頁設計師合作專案，時薪600，須具備UI/UX設計能力。',
            salary: 600,
            exposurePlan: '黃金曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/a9a6d67c-2a24-41d3-96df-abb825fc8b42.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=o42VPk226KLvF%2FwU3b4meMi%2BcNz7SWalhLovKDRvdFYh5Uoj%2BX%2FW55jrkUKFGCgzPRicOYXctUHjB9BmE0As5dSRoHtvzhpp1aHAt4r%2BDlVfgEUsoaliQUf9urGJSbohAJdzqqDIN%2BkxROZDrR8vstNO19IBaYd7%2BRRS8OC%2BWCSI6ol07MATgX4XKQz3QTYDb1UhgfCzqHDGmTjMeFtOy2p8iW%2FDhZUrLXhbDmzCQW6twfHUrRR0ui5%2Fl%2BAtJS8ICIDo7EqPfn54fwTSl%2BiKzRusjzxLg5mS9kp4TVo2HieyHYPa3VwZhkp1TGqbhq2l5HRaklCsROHMEi%2Bplb3y2g%3D%3D',
            ],
            contactInfo: {
                name: `${userCase1.lastName}${userCase1.firstName}`,
                phone: userCase1.phone,
                email: userCase1.email,
            },
            location: {
                city: '臺北市',
                dist: '內湖區',
                address: '瑞光路581號',
                longitude: 121.5681287,
                latitude: 25.0799209,
            },
            isUrgent: false,
            helpers: [
                {
                    helperId: userCase5._id,
                    status: 'waiting',
                },
                {
                    helperId: userCase4._id,
                    status: 'waiting',
                },
                {
                    helperId: userCase3._id,
                    status: 'waiting',
                },
                {
                    helperId: userCase2._id,
                    status: 'waiting',
                },
            ],
            time: {
                createdAt: new Date(new Date().setDate(new Date().getDate() - 10)),
                updatedAt: new Date(new Date().setDate(new Date().getDate() - 5)),
                publishedAt: new Date(new Date().setDate(new Date().getDate() - 5)),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: null,
                submittedAt: null,
                confirmedAt: null,
                completedAt: null,
                expiredAt: new Date(new Date().setDate(new Date().getDate() + 25)),
            },
        },
        {
            userId: userCase1._id,
            status: 'published',
            title: '需求運動教練',
            category: '運動陪練',
            description: '尋找有經驗的運動教練進行團體訓練，時薪450，場地提供。',
            salary: 450,
            exposurePlan: '限時黃金曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/e1e193f1-4e06-4e33-af9a-2bf582c55b14.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=EB5m3spRNsetk7WF0Nd170eUp%2FAfqYlG4w0PWRiW99L%2FAkfm%2BuDJHxda8qTbuSryF6%2FJ0acZZOccB3kPi1NEkKjJOMCrxJMoMez%2ByPsnMb2pe74wA3Upucu2SOkmdyZnHOCgorn3v2RytpyzPKB3YZ0slDFPCA7XhfIpNUsLtT6gJkfPcXfHUiUm2Z3K%2FZPv5ciVjx5wW8JHZN1kEsThBDcjZbmOkrvejFpl2oiBO8XmcYA3bwZIBM61RZ7%2FaZN8wfvqITeeQswBO7uDpBj21ko4%2FlyunIdvdHwru%2B7o0wVAQk%2BSmy9Ws72kiinjK8rh46IfuBc%2FzF0jPsXTQOBKNg%3D%3D',
            ],
            contactInfo: {
                name: `${userCase1.lastName}${userCase1.firstName}`,
                phone: userCase1.phone,
                email: userCase1.email,
            },
            location: {
                city: '臺北市',
                dist: '大安區',
                address: '光復南路300號',
                longitude: 121.5574241,
                latitude: 25.0391323,
            },
            isUrgent: true,
            helpers: [
                {
                    helperId: userCase4._id,
                    status: 'waiting',
                },
                {
                    helperId: userCase3._id,
                    status: 'waiting',
                },
                {
                    helperId: userCase2._id,
                    status: 'waiting',
                },
            ],
            time: {
                createdAt: new Date(new Date().setDate(new Date().getDate() - 10)),
                updatedAt: new Date(new Date().setDate(new Date().getDate() - 3)),
                publishedAt: new Date(new Date().setDate(new Date().getDate() - 3)),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: null,
                submittedAt: null,
                confirmedAt: null,
                completedAt: null,
                expiredAt: new Date(new Date().setDate(new Date().getDate() + 27)),
            },
        },
        {
            userId: userCase3._id,
            status: 'published',
            title: '需要翻譯人員',
            category: '文書處理',
            description: '招募翻譯人員協助會議翻譯，時薪1550，需要擅長英文和中文。',
            salary: 1550,
            exposurePlan: '限時曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/5491cce3-28a3-41df-b74e-c223a22ddc34.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=jt25T2H3muNzDgpsGeA1ssVJHXo7ptkp429aXA7qUCB6m80%2Fw94xFUHn8smB5zE2XoUsz%2Fi%2FdxA%2BFww%2BKavaAIxq2MksDLazpggrkQRsmksXu8FaiyCfsUEqTEe0qFD2bdrvpeOW15CaKcpXzUxrUIT4q4TcNtqj5O5klYIacWGsJNcwJbNhNqWFsMI4VBYLahXSXdK9pPCMfHajqppC6BDFJx7oN8omFdiknx5OMijKbF7kw4qEbyyFge25PT%2FhifgnMGWSHuGkNbuMIJ%2F3Q3Ajmj%2FJjaUMuS9i5jhb8cXyAd0VJaLHLfrN9cKHoVgKjAa2vvp5xV6j%2FdNrH0dL5g%3D%3D',
            ],
            contactInfo: {
                name: `${userCase3.lastName}${userCase3.firstName}`,
                phone: userCase3.phone,
                email: userCase3.email,
            },
            location: {
                city: '臺北市',
                dist: '大安區',
                address: '忠孝東路四段216巷38號',
                longitude: 121.5528545,
                latitude: 25.0395291,
            },
            isUrgent: true,
            helpers: [
                {
                    helperId: userCase2._id,
                    status: 'waiting',
                },
            ],
            time: {
                createdAt: new Date(),
                updatedAt: new Date(),
                publishedAt: new Date(),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: null,
                submittedAt: null,
                confirmedAt: null,
                completedAt: null,
                expiredAt: new Date(new Date().setDate(new Date().getDate() + 7)),
            },
        },
        {
            userId: userCase3._id,
            status: 'published',
            title: '好想吃南部粽',
            category: '排隊代購',
            description: '幫忙去南部買南部粽',
            salary: 1000,
            exposurePlan: '限時曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/21fdf0d3-4956-43fb-85db-f852d88e6f1a.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=bSjSH8C7mUTIn1WkjIT8d61%2FcTEI92aYRC9Df3uYO6T97Id9cyOmrROcxEnxYzXzaczeiBVRMq%2FiB6ZrOzvxr8Is1yciy%2BY7S4cClOk%2FxZPPrLMlOTDwp8hRD%2FiqXKmA7rAQwreesU%2FdDx0B%2F77vJI9X%2FHKZvibbivpsVpsf1UpYh8amfRJ8uJv4aXtxoduUjynFlVsG8d9H3nz5q6KuTKg5logZ7G4nBEdLXDNSSGNgW4AELbjFOIL5own%2B4AHW1PpbnQ%2Fqi%2BURJ%2Base89gTGDiBr9Q04LjOBGLleH4eCYfPkDduePbD3nWKkbltu%2F8qYFOO1SogglKNLWxdbJFmQ%3D%3D',
            ],
            contactInfo: {
                name: `${userCase3.lastName}${userCase3.firstName}`,
                phone: userCase3.phone,
                email: userCase3.email,
            },
            location: {
                city: '臺北市',
                dist: '大安區',
                address: '新生南路二段1號',
                longitude: 121.5362545101697,
                latitude: 25.02976561184247,
            },
            isUrgent: true,
            helpers: [
                {
                    helperId: userCase2._id,
                    status: 'waiting',
                },
            ],
            time: {
                createdAt: new Date(),
                updatedAt: new Date(),
                publishedAt: new Date(),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: null,
                submittedAt: null,
                confirmedAt: null,
                completedAt: null,
                expiredAt: new Date(new Date().setDate(new Date().getDate() + 7)),
            },
        },
        {
            userId: userCase2._id,
            status: 'published',
            title: '李多慧後援會',
            category: '活動支援',
            description: '在比賽或活動期間指導啦啦隊成員進行精彩的舞蹈表演、鼓勵觀眾參與互動，並提供整體支援，以確保活動達到最佳效果。',
            salary: 5000,
            exposurePlan: '限時曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/88deabe1-b0a4-4a34-be0e-4476139ead50.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=nYQYBvEs799H46gZgLANSRuAOcGsc%2Fd57wr5uFKz7%2Bhk5V5xULhwH0AcsH3JYbnyR%2FSMhLjIpzkrLXuD%2F2x42f8zIUHRkMMMekjvgkDMsOUyA0hBMaFfpqQUkBdvyd3QazwXegGxboWGZARdr7oeFb9eTcu1emIxuIwPdv7hcIAESDimnPolEz5%2BSdmQdFDSI0o0UW4LP7u0KcauDjhubAAcI16ggOi%2FvBMmQh%2B%2BeOG80nEFxmMyc2gNTgzcRkUOzwYl4kYLslD%2FhV1Tm7HS0ta6yy9Z3xQsFV%2F38GtsLhWdIKFGUIqWdrVTqsR5CUfebtTaS390g7822enARtuv6w%3D%3D',
            ],
            contactInfo: {
                name: `${userCase2.lastName}${userCase2.firstName}`,
                phone: userCase2.phone,
                email: userCase2.email,
            },
            location: {
                city: '新北市',
                dist: '新莊區',
                address: '中華路一段75號',
                longitude: 121.45186948318613,
                latitude: 25.040725128951557,
            },
            isUrgent: true,
            helpers: [
                {
                    helperId: userCase5._id,
                    status: 'waiting',
                },
            ],
            time: {
                createdAt: new Date(),
                updatedAt: new Date(),
                publishedAt: new Date(),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: null,
                submittedAt: null,
                confirmedAt: null,
                completedAt: null,
                expiredAt: new Date(new Date().setDate(new Date().getDate() + 7)),
            },
        },
        {
            userId: userCase2._id,
            status: 'published',
            title: '蘋果發表會的產品試用心得',
            category: '寫評分享',
            description: '請拍攝一支影片介紹 Apple Vision Pro，文案需提及功能、優點',
            salary: 3000,
            exposurePlan: '限時曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/6b9ede72-e959-410b-91f2-170461916dd8.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=bzqwT9cOvRm9SuO%2FO3XXrtOc6jesatfrTkZhsxFWn%2BZz0Qro8fPXvHB1VWDEI%2F36ddGtnmp0EOgNooA%2FiAegys%2FxvYAJa0mk02f%2FPIysWitg4Qw9NbHqmWQPjBoSRnZaSZ8LBotNJJim1LUARaBgGhrQw0ywSzFUAgf1wHVVmn4nPctk7exwZILnXUH2h4BykN3szceQ8O41yBRWJw%2FPcrVPh7FcZnSMauA%2FDNDliyzYNlFRS38tU4XL9o900RHen1s4w%2BBin7S6kNhg1b4qA0YAFRAHcqkmMMP8Lia%2F4Gh%2FYNaCxc2nwRQftNHf9%2F8iVnxiafbp%2BM0rGNkDehSxbg%3D%3D',
            ],
            contactInfo: {
                name: `${userCase2.lastName}${userCase2.firstName}`,
                phone: userCase2.phone,
                email: userCase2.email,
            },
            location: {
                city: '臺北市',
                dist: '中山區',
                address: '南京西路15號',
                longitude: 121.52067266187575,
                latitude: 25.055386636761163,
            },
            isUrgent: true,
            helpers: [
                {
                    helperId: userCase1._id,
                    status: 'waiting',
                },
            ],
            time: {
                createdAt: new Date(),
                updatedAt: new Date(),
                publishedAt: new Date(),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: null,
                submittedAt: null,
                confirmedAt: null,
                completedAt: null,
                expiredAt: new Date(new Date().setDate(new Date().getDate() + 7)),
            },
        },
        {
            userId: userCase2._id,
            status: 'published',
            title: '羽球教練',
            category: '運動陪練',
            description: '我需要一位專業的羽球教練，最近想學殺球，大概需要三個小時',
            salary: 3600,
            exposurePlan: '限時曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/32b0b904-91d1-42d2-8a3e-7eb51286f1d4.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=Jx8mFCSSkI8X%2FJ7udVREtr9gWUkiHZqgSN1GA6q6AVVszfI3wP2h%2FqJ%2F1UOM5pU%2FSBogRzJcm0%2FSvYveaF9%2BSzpBun5toYQNbxwF5mgqD4LW5G5qo2boLkqSEmRx1WkjRsAcOY5%2BKJBk1mjAERZf1p0pB5079o9Z825GP7yxRiHHdyHrXd4LDuYEonzfCOxF%2Ffax%2FX%2Bs0BGDUXiTHoCvTHPYU4nFJQ4IiYsdLX5KRQZngWGpL6es259VabqAWzW2lazXd1uD0nP4wuKNzhH%2BsIbePR081CBL%2BZzVvVOPUtkju1ypuRd7CLr4bC3cMC%2BjICQEAqR3uCXrNaxTsnPqcA%3D%3D',
            ],
            contactInfo: {
                name: `${userCase2.lastName}${userCase2.firstName}`,
                phone: userCase2.phone,
                email: userCase2.email,
            },
            location: {
                city: '臺北市',
                dist: '松山區',
                address: '南京東路四段10號',
                longitude: 121.55215931468928,
                latitude: 25.051833133387927,
            },
            isUrgent: false,
            helpers: [],
            time: {
                createdAt: new Date(),
                updatedAt: new Date(),
                publishedAt: new Date(),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: null,
                submittedAt: null,
                confirmedAt: null,
                completedAt: null,
                expiredAt: new Date(new Date().setDate(new Date().getDate() + 7)),
            },
        },
        {
            userId: userCase2._id,
            status: 'published',
            title: '居家風水',
            category: '其他內容',
            description: '我需要一位老師幫忙看居家裝潢',
            salary: 2000,
            exposurePlan: '限時曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/69fc7346-14e6-4fec-b821-a9bd70356f45.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=G4VapSh9SeVSx%2FJVTUzk5DIIELgCDWImeB2wsUb7VgJSTdRcDAUEGGNdMYpOHaE6ytkmm4BQo5ie9eJye%2FsG61oSLWnlhXnb0hE9rHd42FLUvAe9X5yQRxw9pY70lK0hvSxnvZxarATOl1FOegUvWj%2BeJOuMXaopdDM7LM%2FEqHye4jIX5o73Ni6eByH3EXPT6lvyzD8ul%2FZGi74FTHDI7SVpSap%2F3KH8ZMQzK6g1%2B61lAbGqnhtbtVEV781ksVkkrB%2Fiu03%2FDXUDz2Zen3BJqFwvRoe9emEIl60EUCaAYmZNcfvwyjKxeeBOSEG8jTz%2Bh8%2BAYwYb64fIxN37AsC0gA%3D%3D',
            ],
            contactInfo: {
                name: `${userCase2.lastName}${userCase2.firstName}`,
                phone: userCase2.phone,
                email: userCase2.email,
            },
            location: {
                city: '臺北市',
                dist: '中正區',
                address: '忠孝東路一段108號',
                longitude: 121.52456874597381,
                latitude: 25.044827114175547,
            },
            isUrgent: true,
            helpers: [],
            time: {
                createdAt: new Date(),
                updatedAt: new Date(),
                publishedAt: new Date(),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: null,
                submittedAt: null,
                confirmedAt: null,
                completedAt: null,
                expiredAt: new Date(new Date().setDate(new Date().getDate() + 7)),
            },
        },
        {
            userId: userCase2._id,
            status: 'published',
            title: '幫忙洗車',
            category: '清潔外包',
            description: '我的車子很髒，請幫忙洗，然後車子內部也需要稍微整理一下',
            salary: 2500,
            exposurePlan: '限時黃金曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/8998712c-5cc1-485a-b9f7-3bb5899b52ad.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=i8ckrQpFp3edbRdglSsA6DjwHXWaQv3bs%2B%2F1MLJpJ7oCQNq%2FpIT%2BeG78BYpr%2F7o%2Bs2UIX34TlOaNAEw13qiluOff2noae8jDMicd1pDVs2xBqUreIzlm8wM76gphechbT8INOHDvECcEY%2FBJuVozQYu6glKtz40uvSOxAAFhj1Qg5m7ofH6ji584Nt3bQMZWQDGR%2F0SqXUPq99OwQ32a9Er5%2BKKRMF1KKlcysdE5nKUsvCLFj3xFK8S%2BoglTgAxtk7TxEScfRcYFtsMJzFeFCt0jLbyJqASkjmdiMNOBC9jUja60nhbU7oeWyqgrWB51R2zp8amAo4yiLNEWw4KimA%3D%3D',
            ],
            contactInfo: {
                name: `${userCase2.lastName}${userCase2.firstName}`,
                phone: userCase2.phone,
                email: userCase2.email,
            },
            location: {
                city: '臺北市',
                dist: '中正區',
                address: '忠孝東路三段300號',
                longitude: 121.54283503941396,
                latitude: 25.042651778183814,
            },
            isUrgent: false,
            helpers: [],
            time: {
                createdAt: new Date(),
                updatedAt: new Date(),
                publishedAt: new Date(),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: null,
                submittedAt: null,
                confirmedAt: null,
                completedAt: null,
                expiredAt: new Date(new Date().setDate(new Date().getDate() + 7)),
            },
        },
        {
            userId: userCase5._id,
            status: 'published',
            title: '吉他伴奏',
            category: '活動支援',
            description: '想陪另一半過生日，所以想要有音樂伴奏',
            salary: 2500,
            exposurePlan: '限時黃金曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/1f392539-959a-4f61-bc32-7daa277ca160.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=Q1Q0TNrG7AP2RE1aKxEISfO5i47rjiga8zZeLS3coCIEs1urumlMuSEoUznFT77Ffh2nRZRKlV8dg9IZJZ%2BsI4XBNRhA4Liy3TjI7urGvEUjQlRm%2Bp1cYG1WaoEjzbR9LmFGB%2BC8bNV5xBwK5ZtjKYJL%2FaaeSwYCX6t4KdMIvhNDPls8d7Iggl3CWo%2Bi1w1bUb3WT7JpDCfkWq1SM%2FxKf3Q0HTY032IP%2Bz4RuEH9Ce77BLObxkA2dwK6hCR72vISfIdtswp3ICy7m0pKtgJ48ogzxjKqVad0wSYGCXRVGkz2shBJTUM4ViEemVyx95yLXO%2B1X6qNUfWGUZNxisUYsQ%3D%3D',
            ],
            contactInfo: {
                name: `${userCase5.lastName}${userCase5.firstName}`,
                phone: userCase5.phone,
                email: userCase5.email,
            },
            location: {
                city: '臺北市',
                dist: '大同區',
                address: '華亭街8號',
                longitude: 121.51279429847479,
                latitude: 25.054315522789942,
            },
            isUrgent: true,
            helpers: [],
            time: {
                createdAt: new Date(),
                updatedAt: new Date(),
                publishedAt: new Date(),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: null,
                submittedAt: null,
                confirmedAt: null,
                completedAt: null,
                expiredAt: new Date(new Date().setDate(new Date().getDate() + 7)),
            },
        },
        {
            userId: userCase5._id,
            status: 'published',
            title: '日文家教',
            category: '家教陪讀',
            description: '家中小女想學日文，希望有N2以上來教他五十音',
            salary: 3300,
            exposurePlan: '限時黃金曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/891b2c57-fd92-48de-aeb6-0957b70430b4.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=WpvexHxinkMaVdJy3HVieZU0YBAe%2BsrbWDSMME0FTdQem9nTj2jopnS2fMAkTYPChgIH878E4ec0bTYlePl91%2BAikGsV93TFUKtGEmn3BZApmp4EhTN1w5b3ikg7NNaK%2Bylf1koyfHvQgLbcGQP0FDPWAnEWQzqNEzse5rTZ17HPRQSaDUmfRVrjjCcr9IVKv6QyO6mAjVkKFB00iNxIaAToRJCK%2BA7KSHX9BpC9zlOzEknF2LnYwfoMpo9tY6B9IB6PkjInqa12VdllS%2FWaLHnJKAbIUduK9xuS940ZqvL%2F%2Bj9QV4gGajNlfj21nH5ZyCchW7eIVDUVtEnSAo7knw%3D%3D',
            ],
            contactInfo: {
                name: `${userCase5.lastName}${userCase5.firstName}`,
                phone: userCase5.phone,
                email: userCase5.email,
            },
            location: {
                city: '臺北市',
                dist: '萬華區',
                address: '莒光路248號',
                longitude: 121.49408320833884,
                latitude: 25.035419699400332,
            },
            isUrgent: true,
            helpers: [],
            time: {
                createdAt: new Date(),
                updatedAt: new Date(),
                publishedAt: new Date(),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: null,
                submittedAt: null,
                confirmedAt: null,
                completedAt: null,
                expiredAt: new Date(new Date().setDate(new Date().getDate() + 7)),
            },
        },
        {
            userId: userCase5._id,
            status: 'published',
            title: 'line貼圖',
            category: '視覺設計',
            description: '我想要有人幫我家的狗狗設計line貼圖',
            salary: 1800,
            exposurePlan: '限時黃金曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/26738557-7f05-4f7b-a290-304e0152802f.png?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=cDWiLe59sRxsxvqAQ1dshQRUYQUDoU%2B8oBI4z9FuyP2wwSZSp5lHGRE4zT7WQOOzo484KIUkOlseNYsQNxZ0izSWvQyW4fe3YZHJnH5kiN5zwMmT0xiA%2BaUoTj8xBUItnJlFq5MlC1ydJU%2BD7lp8OjJ8gnLD92nA%2FVJQoeoQ0zjo5RXZsLRp18Y9KpJcLgYMl2MzrO%2BRfiyYbKWSP5P9xlrQbTDREpCnUhl0qsu4T6GcsYzlyEzHpNKItkg7VC1wopQ%2BJsTlBuyn5GE1sg0FxPGw8b6JtKxOFTLsd7kpT5C5rkFjOjx3e23N%2Bsu4DF8NM23H508WmwQecDbAitLLDQ%3D%3D',
            ],
            contactInfo: {
                name: `${userCase5.lastName}${userCase5.firstName}`,
                phone: userCase5.phone,
                email: userCase5.email,
            },
            location: {
                city: '新北市',
                dist: '三重區',
                address: '光復路一段67號',
                longitude: 121.47236558669216,
                latitude: 25.04972400190629,
            },
            isUrgent: false,
            helpers: [],
            time: {
                createdAt: new Date(),
                updatedAt: new Date(),
                publishedAt: new Date(),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: null,
                submittedAt: null,
                confirmedAt: null,
                completedAt: null,
                expiredAt: new Date(new Date().setDate(new Date().getDate() + 7)),
            },
        },
        {
            userId: userCase5._id,
            status: 'published',
            title: '一起唱歌',
            category: '人力派遣',
            description: '心情不好，想要找人一起Ｋ歌 我會點很多情歌哦～',
            salary: 3000,
            exposurePlan: '限時黃金曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/14d1bc51-a96c-4a56-a4ad-301a5de1e560.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=Z%2BRRzHSdULlJ3WSnduP5OHCC3hfwnw9FZgaqFRPhEyIGPb%2FIyFRElOWSzdOULe5jXnqIfaS8Z4GwB6cXek1hVBw4P4HbV9h4kRXvG%2FGQgtcdPVoUN0hxn8vsPKUE8C6ci%2B5Boq5Xt8fvF99EoY6%2FgtMww%2B0iucHbCcCZ5Qr4sW2HkEqghAAM0lIrdFN4x5TOC6%2BaRJrIVVxSNlO5H50iQI9cAlTDHa8Ev2TaNIO86jL9DdAc1Rj%2BhLHHQtOkScftCPbwd6%2B5MzH4McyWAkU64VjDSsM0zLnNMP2lDLC6ftyJl68x%2F5vy7htEvWjgSVSdvFZRV3j68tr%2B0g3evR%2BQfw%3D%3D',
            ],
            contactInfo: {
                name: `${userCase5.lastName}${userCase5.firstName}`,
                phone: userCase5.phone,
                email: userCase5.email,
            },
            location: {
                city: '臺北市',
                dist: '中山區',
                address: '錦州街19號',
                longitude: 121.5249984979749,
                latitude: 25.0612225983483,
            },
            isUrgent: true,
            helpers: [],
            time: {
                createdAt: new Date(),
                updatedAt: new Date(),
                publishedAt: new Date(),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: null,
                submittedAt: null,
                confirmedAt: null,
                completedAt: null,
                expiredAt: new Date(new Date().setDate(new Date().getDate() + 7)),
            },
        },
        {
            userId: userCase5._id,
            status: 'published',
            title: '吃大餐',
            category: '餐飲烹飪',
            description: '想吃一頓高級私廚料理',
            salary: 6666,
            exposurePlan: '限時黃金曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/f6318ebe-4d9b-4328-9019-9bbcdf761f7b.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=vOs765RIav2RbSPg2RmlxOC4VBoABVJQceGRxotDjpFY%2Fd64esu36QI59mYrwqu7RF1Z2KyjaoBhHv472%2FjwkmIyTfujRJY6hTN7uoEw174UX6XSdLQY7GX1z0xujR5skGj193ZmEclha3JXMQdNDYWENRHTPPggCu77NCZymQV2dUn2pM3KZKMfHKYmjrtnIxnQOmspOkZVBnvMd2MW0RlCjAcdzsNkBAy02AaKvvDEeaXHQ0QKDb1XSBbByAhROlWAdfwhSv1NgeLsvU2unvF6i7k6CnDJVOXooNpq%2FxhC4BGY8u9i4iBm0WC6VnWezzH7KFW%2FFT%2BUR11YBnZZ5w%3D%3D',
            ],
            contactInfo: {
                name: `${userCase5.lastName}${userCase5.firstName}`,
                phone: userCase5.phone,
                email: userCase5.email,
            },
            location: {
                city: '臺北市',
                dist: '大安區',
                address: '忠孝東路四段40巷13號',
                longitude: 121.54478247162169,
                latitude: 25.04166685884983,
            },
            isUrgent: true,
            helpers: [],
            time: {
                createdAt: new Date(),
                updatedAt: new Date(),
                publishedAt: new Date(),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: null,
                submittedAt: null,
                confirmedAt: null,
                completedAt: null,
                expiredAt: new Date(new Date().setDate(new Date().getDate() + 7)),
            },
        },
        {
            userId: userCase5._id,
            status: 'published',
            title: '媽媽想學鋼琴',
            category: '家教陪讀',
            description: '我媽媽想學鋼琴，想找音樂老師教學',
            salary: 6666,
            exposurePlan: '限時黃金曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/c8fbcc29-36c4-42b8-b207-dee24ef9fa72.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=vEKxlXkSWjZNoMmhhMORAUYkZI46D0Sodz7oHpOjTIsr4D4k50byV%2FmgG%2FANpxSVfRU5ltpjV1vMBykCoYVIcn5ugPk4sRWAvKUneuswul7R1atxSGrhDAt9irCwgb8STBKocn%2FBQ713QTtcXfVQxSdQnyZZaeBJdx3wp0kvfk45VgIXjdMXFfy%2Fkd%2Fz%2BjcbfPcN9qg3YAUgEFfri4%2BT51JGof4g%2FFl9Oh83ncUOupeX%2FJHlUwHsY5%2B%2BSIppjvuR20%2Bb7FCX2G1e4siJL3jqCaJrOd3PaCCqyTKv62Ku0ZjIfzJAYQgXTMHxklew8EBCC%2FZbo7nMvTxta2aRyM8jKw%3D%3D',
            ],
            contactInfo: {
                name: `${userCase5.lastName}${userCase5.firstName}`,
                phone: userCase5.phone,
                email: userCase5.email,
            },
            location: {
                city: '臺北市',
                dist: '文山區',
                address: '興隆路三段112巷2弄13號',
                longitude: 121.55693088112557,
                latitude: 25.000890941610397,
            },
            isUrgent: false,
            helpers: [],
            time: {
                createdAt: new Date(),
                updatedAt: new Date(),
                publishedAt: new Date(),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: null,
                submittedAt: null,
                confirmedAt: null,
                completedAt: null,
                expiredAt: new Date(new Date().setDate(new Date().getDate() + 7)),
            },
        },
        {
            userId: userCase5._id,
            status: 'published',
            title: '總統大選隨機詢問',
            category: '市場調查',
            description: '請幫忙詢問30個人，關於總統大選候選人的意見',
            salary: 5555,
            exposurePlan: '一般曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/75b0a4d3-4dab-4933-8d0e-951fef40d3b3.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=AS75RiZl%2BKxHxaiVfcWlKtz44oDl5XNkb3y16pfWFfce3Cw5GXfshIUGb%2BNPKZl8j4R1Ggrcd6zfIzKw6rcdJI8z4JODnay0MTtWq6Gs6z%2F2hg0S98X9uFFDWMT0E7Pw8wZgDkjvSL2OHRnTRCR33UHd5rpP3fd7KVa%2B9O10eCJfq4B42P16miwJG%2FAMSsO7IGSxTrg0Yjggp7Jcl9ArN%2BFz0TYFgQ8i5JbqA3cfk9CHY3m5qheMGREwJPrM3td0wQY686ooSG6xcJvstQPf9LUDSzmvneD4SDYNparETiZ1LNK4ysIG%2Bk4fzP8IuOK%2FEG%2Bwu4Uw5uHtAemwGvuFOQ%3D%3D',
            ],
            contactInfo: {
                name: `${userCase5.lastName}${userCase5.firstName}`,
                phone: userCase5.phone,
                email: userCase5.email,
            },
            location: {
                city: '臺北市',
                dist: '大安區',
                address: '羅斯福路四段1號',
                longitude: 121.53967613653329,
                latitude: 25.01766796629275,
            },
            isUrgent: false,
            helpers: [],
            time: {
                createdAt: new Date(),
                updatedAt: new Date(),
                publishedAt: new Date(),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: null,
                submittedAt: null,
                confirmedAt: null,
                completedAt: null,
                expiredAt: new Date(new Date().setDate(new Date().getDate() + 7)),
            },
        },
        {
            userId: userCase2._id,
            status: 'published',
            title: '烘焙證照',
            category: '餐飲烹飪',
            description: '下個月考丙級烘焙證照，請幫忙加強訓練巧克力瑞士捲、布丁檸檬派、泡芙',
            salary: 600,
            exposurePlan: '一般曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/e017d5dd-a168-4f43-9997-a302f6ae99f2.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=g9ypItHSc6O%2BT3H0O%2BstmFkVC1Ym610Erj%2BYWTeAhb7Y%2FgYva2j6BeFJgzSmIZNQ5FOhvKRpUT3E2syQlud3ogw3PJU5eGCLHV%2FKlJCYofXxIM%2Bmg57%2FQaiCSHMldpKJeFYu73RjOqSFK0OwwP0U61fYa9%2BJazSMZ4CCcJegfPQpIm5uunoianJ5lbwxurJajxJCwY3PfpxDivV8PgjJ%2FBRSvW3oGySRznQK1aUlyBqCzz2fa0GQAFuXo6nFPIN%2BjTHHTVkX62uzuGXNA2jCFJCCZXmpiQ5i5jFV%2B3BpbBD7s%2BfNxSbYO9sQlUMg4SxlljZoMHe%2FevIgqxaffdI3wg%3D%3D',
            ],
            contactInfo: {
                name: `${userCase2.lastName}${userCase2.firstName}`,
                phone: userCase2.phone,
                email: userCase2.email,
            },
            location: {
                city: '臺北市',
                dist: '大安區',
                address: '敦化南路二段265巷13號',
                longitude: 121.54885394229228,
                latitude: 25.026303380435976,
            },
            isUrgent: false,
            helpers: [],
            time: {
                createdAt: new Date(),
                updatedAt: new Date(),
                publishedAt: new Date(),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: null,
                submittedAt: null,
                confirmedAt: null,
                completedAt: null,
                expiredAt: new Date(new Date().setDate(new Date().getDate() + 7)),
            },
        },
        {
            userId: userCase2._id,
            status: 'published',
            title: '幫忙撥蝦子',
            category: '餐飲烹飪',
            description: '我大概有60隻蝦子要剝殼，頭不可剝掉',
            salary: 600,
            exposurePlan: '黃金曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/938db7ab-33ea-4275-8d89-9d02db3f4fff.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=dkBbTz0ccb3EQQEOWl6bu1rfTeJ%2B4HRLN79jXEw0XGJsnoOj1XqJR9Kip5YU03eFdYrYXmSM9vzoqd1mzvAshaMnb3yJCQDg5k0vaJYSyFFv5NYfMlMiMPUO9HLpKiIFU%2BqiA%2FuGq3PyxOVhJ2B1MmOME%2BJMGRp3PYs1xuFA0Cn9O5qGHaALo5lzVtIKK0Sv8RXYY4aQCOjIj8stc57AE71APfpeZWDwyn8ql9IVnVfrT4aRAwMe2n6Ir8761yOQXuPdmJOVSjq%2B%2FY2ioi4VM4GdWqhya5VUjy82medt7HMFfergbTzmq%2F4hmnf1v3Llj6gQzUfaq%2BGYZ1dXl4Q6Qw%3D%3D',
            ],
            contactInfo: {
                name: `${userCase2.lastName}${userCase2.firstName}`,
                phone: userCase2.phone,
                email: userCase2.email,
            },
            location: {
                city: '臺中市',
                dist: '西屯區',
                address: '國安一路168號',
                longitude: 120.61229956605048,
                latitude: 24.194680685868224,
            },
            isUrgent: false,
            helpers: [],
            time: {
                createdAt: new Date(),
                updatedAt: new Date(),
                publishedAt: new Date(),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: null,
                submittedAt: null,
                confirmedAt: null,
                completedAt: null,
                expiredAt: new Date(new Date().setDate(new Date().getDate() + 30)),
            },
        },
        {
            userId: userCase2._id,
            status: 'published',
            title: '影片需要剪輯高手',
            category: '餐飲烹飪',
            description: '我們正在尋找一位熟練的影片剪輯高手來協助我們完成一個專案。這個專案需要將提供的影片素材剪輯成一個流暢且吸引人的結果。',
            salary: 12000,
            exposurePlan: '黃金曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/b94cf323-e3f7-458c-b0fc-18ca4940e714.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=OWfFilUdifjbEze1zRh3brcV3WMKKiRe3lNYxOUqn5gYfE0gPh4%2FnW%2B3IDlY8QeE9r%2BtnZgPwRikVppYBDPVX0eZbNiGzPAs5I3NSuSVi06lSDcXsNcrMnN7hkQHk85UJ%2FF3ccZiu088Q7GakUuzCRu1NyAAm%2B3MO8eFu58fHJJ4xVs6mhg3aILuvaaE1QtbV%2FWG0qosx2DK6hHv%2Fd1Mg3bu%2FcwKMcMUDfu5rkTq6W1wpdegC3fOFDlyPHnf0aWwaPxU8iKM5CQKqycHAfoz8fZbdCwyZaKbI3BEGPQzSJJXEq%2BBeCSa1dnSjF2se8LRVLT63h6Ktp1V9BdZAhLEHw%3D%3D',
            ],
            contactInfo: {
                name: `${userCase2.lastName}${userCase2.firstName}`,
                phone: userCase2.phone,
                email: userCase2.email,
            },
            location: {
                city: '臺中市',
                dist: '北區',
                address: '錦新街40號',
                longitude: 120.6874116831491,
                latitude: 24.15461511691554,
            },
            isUrgent: false,
            helpers: [],
            time: {
                createdAt: new Date(),
                updatedAt: new Date(),
                publishedAt: new Date(),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: null,
                submittedAt: null,
                confirmedAt: null,
                completedAt: null,
                expiredAt: new Date(new Date().setDate(new Date().getDate() + 30)),
            },
        },
        {
            userId: userCase2._id,
            status: 'published',
            title: '我家天花板漏水',
            category: '其他內容',
            description: '如圖，天花板漏水很嚴重，需要師傅幫忙ＲＲＲ',
            salary: 15000,
            exposurePlan: '黃金曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/48edef5b-5ee2-4382-b15c-053e1065cb7b.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=DF09MvokzJ8E9WZg1O8nIZ40qrR0FRBpRZDpevjVf9UDlQD9Fwh2sR3NRbO2RkGaV%2BsAJUkpfx1pLHEA4Slz4z55NGmcCkHTo3KIcX3rep6nqSJff6PZ%2BtjTJS5d9p7oFUlb6ZKaS8FuPvbeUL%2FOp85CJ2Bm7TSzDT5vE8x%2F5N6wVnVmeLejSGov91NVWcefEhfg7jsMbESHQ7INuO9VwMfnCH4chChrJh4f%2FDWN9dR6NxdV7ZNS5XGnb4Wd1jr7cvqOrE1erRRQtuy%2BJEugYAwUb%2B0feB3CNRh1AAtaWYGQvirEJDPhCXzPNqMdNcvaK803dNAZ4Z%2BccSNxTlPgpg%3D%3D',
            ],
            contactInfo: {
                name: `${userCase2.lastName}${userCase2.firstName}`,
                phone: userCase2.phone,
                email: userCase2.email,
            },
            location: {
                city: '臺中市',
                dist: '南區',
                address: '復興路一段359號',
                longitude: 120.65399059014922,
                latitude: 24.1169814764334,
            },
            isUrgent: false,
            helpers: [],
            time: {
                createdAt: new Date(),
                updatedAt: new Date(),
                publishedAt: new Date(),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: null,
                submittedAt: null,
                confirmedAt: null,
                completedAt: null,
                expiredAt: new Date(new Date().setDate(new Date().getDate() + 30)),
            },
        },
        {
            userId: userCase2._id,
            status: 'published',
            title: '徵韓國伴遊',
            category: '活動支援',
            description: '我們團都不會韓文，需要一位導遊一起去首爾5天4夜，從臺中機場開始接送哦～',
            salary: 31200,
            exposurePlan: '黃金曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/74af9df0-4f6e-4781-8b5a-d2ef0c130f9f.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=qj4YC2og87FBWsuwnx6WBfZgtVO1p%2F9pfdn4N%2BmlZdUmX4TReBUf7agvTBnjGht%2Bcudt%2B%2B1m5gozoWetzwUBEoDxnaneq5g2otTFKm9xd5GDIDJWT7ugeubz4GHUBQ2KQTA%2BknUu%2BLC8P9eoi3g13LC9uL3g2np5oyGMqMYTJNM6LeHTU0Y0Pz3j2lOP2U2FJx8lcLbZMGQZ3xYJhnNoH9z5yGay7t9ffk6fqWHxBZlOl0e2RJXzzv6DvbkP781115of%2F0r2dJ4yPSkEpxkk2a0Z4J6%2FZs7UiiUWlTNSNIgliazZe7nQxgRy%2F%2F4ZpkZGiiJgPCO3YWU9hwJ0OKTqdg%3D%3D',
            ],
            contactInfo: {
                name: `${userCase2.lastName}${userCase2.firstName}`,
                phone: userCase2.phone,
                email: userCase2.email,
            },
            location: {
                city: '臺中市',
                dist: '沙鹿區',
                address: '中航路一段168號',
                longitude: 120.5995155997547,
                latitude: 24.25740986113611,
            },
            isUrgent: false,
            helpers: [],
            time: {
                createdAt: new Date(),
                updatedAt: new Date(),
                publishedAt: new Date(),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: null,
                submittedAt: null,
                confirmedAt: null,
                completedAt: null,
                expiredAt: new Date(new Date().setDate(new Date().getDate() + 30)),
            },
        },
        {
            userId: userCase2._id,
            status: 'published',
            title: '徵密室逃脫夥伴',
            category: '活動支援',
            description: '我們缺人，需要一位智慧高於常人的夥伴來破解',
            salary: 2400,
            exposurePlan: '黃金曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/0ac4a471-0323-4a6b-b605-7b1dcb0513e4.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=JPxLNp49E%2BZNa5Jod%2FWOb1o6u1SL%2BG3HiMOI8At6MNgFdnxUDwqmW0YQvxxVzma7bs9dOVRNfKnEqakkadpL9YkUbhlagB3pOmiU%2F%2F1bxaZGROJ0p94%2F8uFUyq1wz4qFiqO0Ekp8oOkGl24YxjeOgfan06gZ8261lcyGbKruK0Te6MgHPbuPtKwwwtjv6YD0hYZiiwh%2FwOK2XPjKxq6DcniHLNEf3lDQdl1euJDcY8CMSLhXxE4KqvCxQR4oEUL61nAHoHbdt2OP7A3JPAMivLWWP81tu%2FX28%2FPs0hlxL3B9Vz73O1krfKw1H8VGp2dnAj2L%2B3e8JdzZpF6fGIiCgg%3D%3D',
            ],
            contactInfo: {
                name: `${userCase2.lastName}${userCase2.firstName}`,
                phone: userCase2.phone,
                email: userCase2.email,
            },
            location: {
                city: '臺中市',
                dist: '南屯區',
                address: '春安路56巷25號',
                longitude: 120.60941110616464,
                latitude: 24.134766287020522,
            },
            isUrgent: false,
            helpers: [],
            time: {
                createdAt: new Date(),
                updatedAt: new Date(),
                publishedAt: new Date(),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: null,
                submittedAt: null,
                confirmedAt: null,
                completedAt: null,
                expiredAt: new Date(new Date().setDate(new Date().getDate() + 30)),
            },
        },
        {
            userId: userCase2._id,
            status: 'published',
            title: '我想學滑雪',
            category: '運動陪練',
            description: '大概有三人想要學滑雪，但大家都是初學者',
            salary: 5600,
            exposurePlan: '黃金曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/d3fbbb7e-b0ca-412f-a5a1-14d4cf0290a1.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=WZC1N9uM0EYzda%2BI91fBVcAO5Cmptg9PBzf3dpEF5QPFhk3c60qdm0dXme8hd3q7t4YNxayjtJuiXEd4VdcLHDaENXKAbsjkIZGAAFHTOnEn6VnGoDEPJ4pEUQShDARA8lkphsOO03%2BvhNHZM2FJEPdMoAtOv%2Bj21R5o8tKT5sS4nYu2ToonKDHVPk4QgpDF0aat2kWbOLW%2B0cFGV33itLqv4jy7KiqzwEyFRkLicwRbKX47fSqZWzGdIPwSOvgLR3tjL1Si7qkp7zGd6Fn4ieoy4exjpndolcDAfxHd9r9Skji9uRsJU14FvPe%2FD8y%2B7IofyPwrOKYVxnRidN4yIg%3D%3D',
            ],
            contactInfo: {
                name: `${userCase2.lastName}${userCase2.firstName}`,
                phone: userCase2.phone,
                email: userCase2.email,
            },
            location: {
                city: '臺中市',
                dist: '中區',
                address: '市府路14號',
                longitude: 120.67997853833619,
                latitude: 24.139951994777977,
            },
            isUrgent: false,
            helpers: [],
            time: {
                createdAt: new Date(),
                updatedAt: new Date(),
                publishedAt: new Date(),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: null,
                submittedAt: null,
                confirmedAt: null,
                completedAt: null,
                expiredAt: new Date(new Date().setDate(new Date().getDate() + 30)),
            },
        },
        {
            userId: userCase2._id,
            status: 'published',
            title: '我想變瘦',
            category: '其他內容',
            description: '最近吃太多，我需要一位營養師幫忙做管理給些建議',
            salary: 3600,
            exposurePlan: '黃金曝光',
            imgUrls: [
                'https://storage.googleapis.com/superhandy.appspot.com/images/6fa10e78-c374-4dea-a8b3-c33656da6ff0.jpeg?GoogleAccessId=firebase-adminsdk-xlymb%40superhandy.iam.gserviceaccount.com&Expires=16756646400&Signature=Tabn6OqscyWI5LhhFayWWDeCQVXH1iv%2FtRlk8Qrn1b1qfhTxkOjf0fqXsGPP%2BBlxaBZzEoUyZpTik9McxWwm7k5b8ZMZfD8hXanh5edU0V9NoSE3vdpqtb3ik2Et3%2F5wdvJB6RS3d5rsU2qfaHuDwm%2BCuegK%2BGQdzWRjuXyZ6cPcTkTIIsF%2BcG50ddl66S1VDP2%2BrGeS7dsdq1BS189IHjKT3UC6YCVtAMTxhDXubEoezFP02xLhOb978XWPppg7IGEmaP%2FRj4euqyo52cnaU%2BxAFz82MY2CLW%2F4UFDA9MxC9OUGqj5WF963qZ0usqJ11QgYCnQfMZMZ1vggZx0TKA%3D%3D',
            ],
            contactInfo: {
                name: `${userCase2.lastName}${userCase2.firstName}`,
                phone: userCase2.phone,
                email: userCase2.email,
            },
            location: {
                city: '臺中市',
                dist: '南屯區',
                address: '大墩路311號',
                longitude: 120.64958188399346,
                latitude: 24.1445184686543,
            },
            isUrgent: false,
            helpers: [],
            time: {
                createdAt: new Date(),
                updatedAt: new Date(),
                publishedAt: new Date(),
                unpublishedAt: null,
                deletedAt: null,
                inProgressAt: null,
                submittedAt: null,
                confirmedAt: null,
                completedAt: null,
                expiredAt: new Date(new Date().setDate(new Date().getDate() + 30)),
            },
        },
    ];

    try {
        // 刪除現有的所有類別
        await Task.deleteMany({});

        // 插入新的類別
        await Task.insertMany(tasks);

        console.log('任務資料初始化成功');
    } catch (err) {
        console.error('任務資料初始化失敗', err);
    }
};

module.exports = initTasks;
